#################################################
# INFRASTRUCTURE YML CONFIGURATION VERSION 3.9  #
#################################################
version: "3.9"

services:
  #################################################
  # PostgresSQL                                   #
  #################################################
  postgres:
    image: postgres:${POSTGRES_SQL_VERSION}
    container_name: ${POSTGRES_SQL_CONTAINER_NAME}
    restart: on-failure
    ports:
      - "${POSTGRES_SQL_PORT}:${POSTGRES_SQL_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_SQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_SQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgre_network

  #################################################
  # PgAdmin                                       #
  #################################################
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: ${PGADMIN_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_USERNAME}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgre_network

networks:
  postgre_network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  postgres:
    external: false
  pgadmin:
    external: false
